spring.application.name=HospitalManagement


#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/hospitalDB
spring.datasource.username=postgres
spring.datasource.password=Sujal@2004$

server.servlet.context-path=/api/v1

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=false

# It is deferred after hibernate creates table we are writing sql manually and putting dummy data
#resource folder ke andar hum joh bhi daalte hai woh classpath ke andar directly daal deti hai
#classpath first path par leke jaata hai hum multiple path daal sakte hai using /
#createAt null kyuki hum initialization karte time data daal rahe hai agar hum proper save method use karte toh aata
#hum testing ke liye local environment mai hum data.sql mai aise data daal ke check kar sakte hai aur yeh teen configuration daalna padega
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql


jwt.secretKey=cwdqdqdqbvdqdhwwgcgwdfwdjwcwchwwcbwcwvgvfbdhkddjvdvdevevevevevievhevelib


#Hume chaiye toh oauth2 ka configuration yaha bata sakte hai ya application.yml mai
spring.security.oauth2.client.registration.google.client-id=898282658299-c9th9shu9ab4hf9bep140f0s78u3k0fp.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

spring.security.oauth2.client.registration.github.client-id=aasdvvsvs
spring.security.oauth2.client.registration.github.client-secret=aasdvvsvs